In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/covid_toy.csv')

In [ ]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [ ]:
X_train.head(3)

    age  gender  fever   cough     city
82   24    Male   98.0    Mild  Kolkata
68   54  Female  104.0  Strong  Kolkata
30   15    Male  101.0    Mild    Delhi

#1.Without column Transfer

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])
X_test_fever = si.fit_transform(X_test[['fever']])

In [ ]:
X_train_fever

array([[ 98.       ],
       [104.       ],
       [101.       ],
       [ 99.       ],
       [100.7260274],
       [101.       ],
       [ 99.       ],
       [ 98.       ],
       [101.       ],
       [101.       ],
       [ 98.       ],
       [ 98.       ],
       [102.       ],
       [ 99.       ],
       [ 98.       ],
       [101.       ],
       [101.       ],
       [100.       ],
       [101.       ],
       [100.       ],
       [100.       ],
       [104.       ],
       [ 99.       ],
       [100.7260274],
       [104.       ],
       [100.       ],
       [102.       ],
       [ 98.       ],
       [ 98.       ],
       [102.       ],
       [101.       ],
       [ 98.       ],
       [104.       ],
       [ 98.       ],
       [ 99.       ],
       [103.       ],
       [104.       ],
       [102.       ],
       [100.7260274],
       [103.       ],
       [101.       ],
       [100.7260274],
       [ 99.       ],
       [101.       ],
       [ 98.       ],
       [ 98.       ],
       [100.       ],
       [103.       ],
       [101.       ],
       [104.       ],
       [ 99.       ],
       [ 98.       ],
       [103.       ],
       [102.       ],
       [101.       ],
       [104.       ],
       [104.       ],
       [101.       ],
       [101.       ],
       [100.       ],
       [100.       ],
       [100.7260274],
       [102.       ],
       [100.7260274],
       [ 98.       ],
       [102.       ],
       [100.       ],
       [103.       ],
       [ 98.       ],
       [104.       ],
       [ 98.       ],
       [103.       ],
       [ 98.       ],
       [104.       ],
       [101.       ],
       [ 98.       ],
       [100.       ],
       [100.7260274],
       [103.       ],
       [104.       ]])

In [ ]:
X_train_fever.shape

(80, 1)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])
X_test_cough = oe.fit_transform(X_test[['cough']])

In [ ]:
X_train_cough.shape

(80, 1)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe  = OneHotEncoder(drop='first',sparse_output=True)
X_train_gender = ohe.fit_transform(X_train[['gender','city']]).toarray()
X_test_gender = ohe.fit_transform(X_test[['gender','city']]).toarray()

In [ ]:
X_train_gender.shape

(80, 4)

In [ ]:
X_train_age = X_train.drop(columns=['gender','city','cough','fever']).values
X_test_age = X_test.drop(columns=['gender','city','cough','fever']).values

In [ ]:
X_train_age.shape

(80, 1)

In [ ]:
X_train_concat = np.concatenate((X_train_age,X_train_fever,X_train_cough,X_train_gender),axis=1)

In [ ]:
X_train_concat

array([[ 24.       ,  98.       ,   0.       ,   1.       ,   0.       ,
          1.       ,   0.       ],
       [ 54.       , 104.       ,   1.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 15.       , 101.       ,   0.       ,   1.       ,   1.       ,
          0.       ,   0.       ],
       [ 22.       ,  99.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 84.       , 100.7260274,   0.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [  8.       , 101.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 14.       ,  99.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   1.       ],
       [ 81.       ,  98.       ,   1.       ,   0.       ,   0.       ,
          0.       ,   1.       ],
       [ 42.       , 101.       ,   0.       ,   1.       ,   1.       ,
          0.       ,   0.       ],
       [ 14.       , 101.       ,   1.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 10.       ,  98.       ,   1.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 12.       ,  98.       ,   1.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 49.       , 102.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 66.       ,  99.       ,   1.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 31.       ,  98.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 68.       , 101.       ,   1.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 19.       , 101.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   1.       ],
       [ 19.       , 100.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 64.       , 101.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [  5.       , 100.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 47.       , 100.       ,   1.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [  6.       , 104.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 25.       ,  99.       ,   1.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 71.       , 100.7260274,   1.       ,   1.       ,   0.       ,
          1.       ,   0.       ],
       [ 12.       , 104.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 19.       , 100.       ,   1.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [  5.       , 102.       ,   0.       ,   1.       ,   0.       ,
          1.       ,   0.       ],
       [ 26.       ,  98.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 71.       ,  98.       ,   1.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 82.       , 102.       ,   1.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 38.       , 101.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 80.       ,  98.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 34.       , 104.       ,   1.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 23.       ,  98.       ,   1.       ,   1.       ,   0.       ,
          0.       ,   1.       ],
       [ 72.       ,  99.       ,   0.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 60.       , 103.       ,   0.       ,   1.       ,   0.       ,
          1.       ,   0.       ],
       [ 51.       , 104.       ,   0.       ,   1.       ,   0.       ,
          1.       ,   0.       ],
       [ 24.       , 102.       ,   1.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 82.       , 100.7260274,   0.       ,   1.       ,   0.       ,
          1.       ,   0.       ],
       [ 83.       , 103.       ,   0.       ,   1.       ,   0.       ,
          1.       ,   0.       ],
       [ 47.       , 101.       ,   1.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 20.       , 100.7260274,   1.       ,   0.       ,   0.       ,
          0.       ,   1.       ],
       [ 65.       ,  99.       ,   0.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 20.       , 101.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 65.       ,  98.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   1.       ],
       [ 34.       ,  98.       ,   1.       ,   1.       ,   0.       ,
          1.       ,   0.       ],
       [ 27.       , 100.       ,   0.       ,   1.       ,   1.       ,
          0.       ,   0.       ],
       [ 73.       , 103.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 34.       , 101.       ,   1.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 16.       , 104.       ,   0.       ,   1.       ,   0.       ,
          1.       ,   0.       ],
       [ 60.       ,  99.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   1.       ],
       [ 83.       ,  98.       ,   0.       ,   1.       ,   1.       ,
          0.       ,   0.       ],
       [ 48.       , 103.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 69.       , 102.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 51.       , 101.       ,   1.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 25.       , 104.       ,   0.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 51.       , 104.       ,   0.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 49.       , 101.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 83.       , 101.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 80.       , 100.       ,   0.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 13.       , 100.       ,   1.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 75.       , 100.7260274,   0.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 20.       , 102.       ,   1.       ,   1.       ,   1.       ,
          0.       ,   0.       ],
       [ 38.       , 100.7260274,   0.       ,   1.       ,   1.       ,
          0.       ,   0.       ],
       [ 64.       ,  98.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 33.       , 102.       ,   1.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 55.       , 100.       ,   0.       ,   1.       ,   0.       ,
          1.       ,   0.       ],
       [ 69.       , 103.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [  5.       ,  98.       ,   1.       ,   0.       ,   0.       ,
          0.       ,   1.       ],
       [ 18.       , 104.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 69.       ,  98.       ,   1.       ,   0.       ,   0.       ,
          0.       ,   1.       ],
       [ 50.       , 103.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 73.       ,  98.       ,   0.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 44.       , 104.       ,   0.       ,   1.       ,   0.       ,
          0.       ,   1.       ],
       [ 65.       , 101.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   1.       ],
       [ 40.       ,  98.       ,   1.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 11.       , 100.       ,   0.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 79.       , 100.7260274,   1.       ,   1.       ,   0.       ,
          1.       ,   0.       ],
       [ 16.       , 103.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 75.       , 104.       ,   1.       ,   0.       ,   1.       ,
          0.       ,   0.       ]])

In [ ]:
X_test_concat = np.concatenate((X_test_age,X_test_fever,X_test_cough,X_test_gender),axis=1)

In [ ]:
X_train_concat.shape

(80, 7)

#With Column Transfer

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
transformer = ColumnTransformer(transformers=[
    ('tnfe',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(drop='first',sparse_output=False),['gender','city'])
],remainder='passthrough')

In [ ]:
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('tnfe', SimpleImputer(), ['fever']),
                                ('tnf2',
                                 OrdinalEncoder(categories=[['Mild',
                                                             'Strong']]),
                                 ['cough']),
                                ('tnf3',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['gender', 'city'])])

In [ ]:
X_train_transform=transformer.fit_transform(X_train)
X_test_transform=transformer.fit_transform(X_test)

In [ ]:
X_train_transform

array([[ 98.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  24.       ],
       [104.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  54.       ],
       [101.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  15.       ],
       [ 99.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  22.       ],
       [100.7260274,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  84.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   8.       ],
       [ 99.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  14.       ],
       [ 98.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  81.       ],
       [101.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  42.       ],
       [101.       ,   1.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  14.       ],
       [ 98.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  10.       ],
       [ 98.       ,   1.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  12.       ],
       [102.       ,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  49.       ],
       [ 99.       ,   1.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  66.       ],
       [ 98.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  31.       ],
       [101.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  68.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  19.       ],
       [100.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  19.       ],
       [101.       ,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  64.       ],
       [100.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   5.       ],
       [100.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  47.       ],
       [104.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   6.       ],
       [ 99.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  25.       ],
       [100.7260274,   1.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  71.       ],
       [104.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  12.       ],
       [100.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  19.       ],
       [102.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,   5.       ],
       [ 98.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  26.       ],
       [ 98.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  71.       ],
       [102.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  82.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  38.       ],
       [ 98.       ,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  80.       ],
       [104.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  34.       ],
       [ 98.       ,   1.       ,   1.       ,   0.       ,   0.       ,
          1.       ,  23.       ],
       [ 99.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  72.       ],
       [103.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  60.       ],
       [104.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  51.       ],
       [102.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  24.       ],
       [100.7260274,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  82.       ],
       [103.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  83.       ],
       [101.       ,   1.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  47.       ],
       [100.7260274,   1.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  20.       ],
       [ 99.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  65.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  20.       ],
       [ 98.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  65.       ],
       [ 98.       ,   1.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  34.       ],
       [100.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  27.       ],
       [103.       ,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  73.       ],
       [101.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  34.       ],
       [104.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  16.       ],
       [ 99.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  60.       ],
       [ 98.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  83.       ],
       [103.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  48.       ],
       [102.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  69.       ],
       [101.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  51.       ],
       [104.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  25.       ],
       [104.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  51.       ],
       [101.       ,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  49.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  83.       ],
       [100.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  80.       ],
       [100.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  13.       ],
       [100.7260274,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  75.       ],
       [102.       ,   1.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  20.       ],
       [100.7260274,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  38.       ],
       [ 98.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  64.       ],
       [102.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  33.       ],
       [100.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  55.       ],
       [103.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  69.       ],
       [ 98.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   5.       ],
       [104.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  18.       ],
       [ 98.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  69.       ],
       [103.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  50.       ],
       [ 98.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  73.       ],
       [104.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          1.       ,  44.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  65.       ],
       [ 98.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  40.       ],
       [100.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  11.       ],
       [100.7260274,   1.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  79.       ],
       [103.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  16.       ],
       [104.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  75.       ]])

In [ ]:
X_train_transform.shape

(80, 7)