In [ ]:
import pandas as pd
import requests

In [ ]:
response=requests.get('https://api.cricapi.com/v1/currentMatches?apikey=your_key')

In [ ]:
data = response.json()

In [ ]:
df = pd.DataFrame(data['data'])

In [ ]:
df.shape

(14, 16)

In [ ]:
df[['id','name','matchType','venue','date','dateTimeGMT','teams']].head(5)

,id,name,matchType,venue,date,dateTimeGMT,teams
0,cc1c57c0-7ecf-4556-8465-47bbac896427,"England vs Pakistan, 2nd Test, Pakistan tour o...",test,"Lord's, London",2026-08-27,2026-08-27T10:00:00,"[England, Pakistan]"
1,d7ad6f40-5f17-4a8e-8552-044453e33b43,"Luxembourg Women vs Belgium Women, 4th T20I, B...",t20,"Pierre Werner Cricket Ground, Walferdange",2026-08-23,2026-08-23T13:30:00,"[Luxembourg Women, Belgium Women]"
2,67c75be2-2cbe-4d4a-9b42-a71277bceab6,"Luxembourg Women vs Belgium Women, 3rd T20I, B...",t20,"Pierre Werner Cricket Ground, Walferdange",2026-08-23,2026-08-23T08:30:00,"[Luxembourg Women, Belgium Women]"
3,1fa3bd8a-4bac-4ebb-b022-aba8281467e3,"Tanzania Women vs Uganda Women, 12th Match, Wo...",t20,"Namibia Cricket Ground, Windhoek",2026-07-28,2026-07-28T12:00:00,"[Tanzania Women, Uganda Women]"
4,d13e1f53-6487-4b61-8b28-84c9833b3e42,"Trinbago Knight Riders vs Saint Lucia Kings, 1...",t20,"Brian Lara Stadium, Tarouba, Trinidad",2026-08-26,2026-08-26T23:00:00,"[Trinbago Knight Riders, Saint Lucia Kings]"

In [ ]:
temp_df = pd.DataFrame()

In [ ]:
for i in range(1,15):
  response=requests.get('https://api.cricapi.com/v1/currentMatches?apikey=1c136084-c578-41c8-8801-2c1045451c63&offset=0'.format(i))
  data = response.json()
  df = pd.DataFrame(data['data'])
  temp_df = pd.concat([temp_df, df], ignore_index=True)

In [ ]:
temp_df

,id,name,matchType,status,venue,date,dateTimeGMT,teams,teamInfo,score,series_id,fantasyEnabled,bbbEnabled,hasSquad,matchStarted,matchEnded
0,cc1c57c0-7ecf-4556-8465-47bbac896427,"England vs Pakistan, 2nd Test, Pakistan tour o...",test,Day 1: 1st Session - Pakistan opt to bowl,"Lord's, London",2026-08-27,2026-08-27T10:00:00,"[England, Pakistan]","[{'name': 'England', 'shortname': 'ENG', 'img'...","[{'r': 29, 'w': 2, 'o': 8.1, 'inning': 'Englan...",4f8f04e8-8c11-402d-9bc3-48c09603d9d8,False,False,True,True,False
1,d7ad6f40-5f17-4a8e-8552-044453e33b43,"Luxembourg Women vs Belgium Women, 4th T20I, B...",t20,Luxembourg Women won by 47 runs,"Pierre Werner Cricket Ground, Walferdange",2026-08-23,2026-08-23T13:30:00,"[Luxembourg Women, Belgium Women]","[{'name': 'Belgium Women', 'shortname': 'BW', ...","[{'r': 194, 'w': 0, 'o': 20, 'inning': 'Luxemb...",2959c81f-9df4-41f8-b9d7-f316975d9677,False,False,False,True,True
2,67c75be2-2cbe-4d4a-9b42-a71277bceab6,"Luxembourg Women vs Belgium Women, 3rd T20I, B...",t20,Luxembourg Women won by 4 wkts,"Pierre Werner Cricket Ground, Walferdange",2026-08-23,2026-08-23T08:30:00,"[Luxembourg Women, Belgium Women]","[{'name': 'Belgium Women', 'shortname': 'BW', ...","[{'r': 121, 'w': 7, 'o': 20, 'inning': 'Belgiu...",2959c81f-9df4-41f8-b9d7-f316975d9677,False,False,False,True,True
3,1fa3bd8a-4bac-4ebb-b022-aba8281467e3,"Tanzania Women vs Uganda Women, 12th Match, Wo...",t20,Tanzania Women awarded the match (opposition r...,"Namibia Cricket Ground, Windhoek",2026-07-28,2026-07-28T12:00:00,"[Tanzania Women, Uganda Women]","[{'name': 'Tanzania Women', 'shortname': 'TAN-...","[{'r': 116, 'w': 2, 'o': 16.4, 'inning': 'Ugan...",3014a459-6e69-4f64-86eb-2f30a2cdbd0b,True,False,False,True,False
4,d13e1f53-6487-4b61-8b28-84c9833b3e42,"Trinbago Knight Riders vs Saint Lucia Kings, 1...",t20,Saint Lucia Kings won by 36 runs,"Brian Lara Stadium, Tarouba, Trinidad",2026-08-26,2026-08-26T23:00:00,"[Trinbago Knight Riders, Saint Lucia Kings]","[{'name': 'Saint Lucia Kings', 'shortname': 'S...","[{'r': 211, 'w': 4, 'o': 20, 'inning': 'Saint ...",929c36f6-9ed6-4cec-a2ad-910a2ee4f701,False,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,2b5a029a-aa13-4d1b-9bbe-cb6446ee7e9b,"Durham vs Gloucestershire, 40th Match, County ...",test,Day 1: 2nd Session - Durham opt to bowl,"Riverside Ground, Chester-le-Street",2026-08-27,2026-08-27T10:00:00,"[Durham, Gloucestershire]","[{'name': 'Durham', 'shortname': 'DURH', 'img'...","[{'r': 106, 'w': 5, 'o': 30, 'inning': 'Glouce...",dfe730c5-873d-44ce-955c-00d82716749b,False,False,True,True,False
388,cb970852-df8b-48bf-8b2f-7098db5e19d9,"Essex vs Surrey, 47th Match, County Championsh...",test,Day 1: 2nd Session - Essex opt to bowl,"The Ambassador Cruise Line Ground, Chelmsford",2026-08-27,2026-08-27T10:00:00,"[Essex, Surrey]","[{'name': 'Essex', 'shortname': 'ESX', 'img': ...","[{'r': 16, 'w': 1, 'o': 6, 'inning': 'Surrey I...",fc9cfc65-4ff6-47c4-baa2-05cc39830e5a,False,False,True,True,False
389,80b734be-dda7-4fbf-bd08-f00321aeb492,"Yorkshire vs Leicestershire, 48th Match, Count...",test,Day 1: 2nd Session - Leicestershire opt to bowl,"North Marine Road Ground, Scarborough",2026-08-27,2026-08-27T10:00:00,"[Yorkshire, Leicestershire]","[{'name': 'Leicestershire', 'shortname': 'LECS...","[{'r': 98, 'w': 2, 'o': 32.3, 'inning': 'Yorks...",fc9cfc65-4ff6-47c4-baa2-05cc39830e5a,False,False,True,True,False
390,72c97402-850a-40a1-93d7-d0466af31471,"Glamorgan vs Hampshire, 49th Match, County Cha...",test,Day 1: 2nd Session - Glamorgan opt to bowl,"Sophia Gardens, Cardiff",2026-08-27,2026-08-27T10:00:00,"[Glamorgan, Hampshire]","[{'name': 'Glamorgan', 'shortname': 'GLAM', 'i...","[{'r': 107, 'w': 5, 'o': 25.1, 'inning': 'Hamp...",fc9cfc65-4ff6-47c4-baa2-05cc39830e5a,False,False,True,True,False
391,3c647e81-d74e-47a3-90fb-e1d3f451d5f6,"Sussex vs Somerset, 50th Match, County Champio...",test,Day 1: 2nd Session - Sussex opt to bowl,"County Ground, Hove",2026-08-27,2026-08-27T10:00:00,"[Sussex, Somerset]","[{'name': 'Somerset', 'shortname': 'SOM', 'img...","[{'r': 96, 'w': 5, 'o': 31.3, 'inning': 'Somer...",fc9cfc65-4ff6-47c4-baa2-05cc39830e5a,False,False,True,True,False

In [ ]:
df['id'].duplicated().sum()

np.int64(0)

In [ ]:
temp_df['id'].nunique()

15

In [ ]:
temp_df['id'].value_counts()

id
cc1c57c0-7ecf-4556-8465-47bbac896427    27
d7ad6f40-5f17-4a8e-8552-044453e33b43    27
67c75be2-2cbe-4d4a-9b42-a71277bceab6    27
1fa3bd8a-4bac-4ebb-b022-aba8281467e3    27
d13e1f53-6487-4b61-8b28-84c9833b3e42    27
d9c33252-aad4-46a8-bc6d-ca87211717a5    27
82fc5df7-fe9f-4970-972f-993a0c251c14    27
0a2f4fd1-eb88-4e99-a527-71a8a34775a4    27
bb130949-5eaa-46ff-89d5-883839da1e3a    27
7d79a71a-0bd5-41eb-8920-6eae1081ba7e    27
2b5a029a-aa13-4d1b-9bbe-cb6446ee7e9b    27
80b734be-dda7-4fbf-bd08-f00321aeb492    27
72c97402-850a-40a1-93d7-d0466af31471    27
3c647e81-d74e-47a3-90fb-e1d3f451d5f6    27
cb970852-df8b-48bf-8b2f-7098db5e19d9    14
Name: count, dtype: int64

In [ ]:
temp_df.to_csv('matches.csv')